apiVersion: v1
kind: Service
metadata:
  name: 'command-sv-spec'
  namespace: 'cqrs-pilot'
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: NodePort
  selector:
    app: 'query-sv'