apiVersion: v1
kind: Service
metadata:
  name: 'query-sv-spec'
  namespace: 'cqrs-pilot'
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: 'query-sv'